### ISSUE TITLE
not compatible with laravel 5.4.8

### ISSUE THREAD

**Issue by Nightly18** [artesaos/defender#109]
``` [ErrorException]
  Declaration of Artesaos\Defender\Traits\HasDefender::newPivot() should be compatible with Illuminate\Database\Eloquent\Model::new
  Pivot(Illuminate\Database\Eloquent\Model $parent, array $attributes, $table, $exists, $using = NULL)
```
need to add $using to satisfy a contract:
- Artesaos\Defender\Traits\Models\Permission@newPivot
- Artesaos\Defender\Traits\Models\Role@newPivot
- Artesaos\Defender\Traits\Permissions\RoleHasPermissions@newPivot

```php
    /**
     * @param Model  $parent
     * @param array  $attributes
     * @param string $table
     * @param bool   $exists
     * @param string|null   $using
     *
     * @return PermissionRolePivot|\Illuminate\Database\Eloquent\Relations\Pivot
     */
    public function newPivot(Model $parent, array $attributes, $table, $exists, $using = null)
    {
    
        ...

        return parent::newPivot($parent, $attributes, $table, $exists, $using);
    }
```

**Comment by torkiljohnsen** [comment]
I can confirm this.

**Comment by torkiljohnsen** [comment]
The issue says 5.4.8, but this change was introduced in 5.4.0, so Defender is really incompatible with all of 5.4.* 

@mauri870 @andreoav See my PR #110. Perhaps that helps.

**Comment by mauri870** [comment]
As @torkiljohnsen said, the method signature of newPivot was changed on 5.4. I'll take a look at this problem soon, sorry for the delay

**Comment by mauri870** [comment]
Have a look at #111

**Comment by pedroskakum** [comment]
same problem

**Comment by nekromoff** [comment]
changing version to `dev-master@dev` in `composer.json` works
(run `composer update` after)

**Comment by vinicius73** [comment]
Now Defender v0.8.x works on Laravel 5.6+
