### ISSUE TITLE
Type error on model: must be of the type array, object given

### ISSUE THREAD

**Issue by guilhermehtk** [artesaos/defender#124]
Quando faço um eager loading no relacionamento de permissions do usuário
return [
            $this->model->with(['permissions:id,name'])->get()
        ];
recebo o seguinte erro Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::__construct() must be of the type array, object given, called in D:\Projetos\App\vendor\artesaos\defender\src\Defender\Traits\Models\Permission.php on line 75.

Quando realizo o "with" com roles isso não ocorre. 
Estou usando o Laravel 5.5.19.

**Comment by ludioao** [comment]
Conseguiu resolver?

**Comment by guilhermehtk** [comment]
Infelizmente não, resolvi migrar para outro pacote.

**Comment by aldoanizio** [comment]
Aparentemente mudou-se a forma de instanciar o model entre as versões do Laravel. O pacote está passando os atributos como a instancia do model porém o construtor necessita de um array com os atributos.

No arquivo: vendor\artesaos\defender\src\Defender\Traits\Models\Permission.php

Altere as linhas:

75: return new PermissionUserPivot($parent, $attributes, $table, $exists, $using);
Para: return new PermissionUserPivot($parent->toArray(), $attributes, $table, $exists, $using);

79: return new PermissionRolePivot($parent, $attributes, $table, $exists, $using);
Para: return new PermissionRolePivot($parent->toArray(), $attributes, $table, $exists, $using);

Foi a forma temporária que encontrei pra solucionar o problema.

**Comment by tnbcc** [comment]
79:return new PermissionRolePivot($parent, $attributes, $table, $exists, $using);
change :  return (new PermissionRolePivot)->fromRawAttributes($parent, $attributes, $table, $exists, $using);
