### ISSUE TITLE
Relationship $role->permissions error on laravel 5.5

### ISSUE THREAD

**Issue by Gabriel-aa** [artesaos/defender#126]
Olá.

Estou tendo o seguinte problema no laravel 5.5.22: quando eu tenho um role e tento pegar trazer suas permissões por relacionamento:

$role->permissions

Recebo o seguinte erro:

`Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::__construct() must be of the type array, object given, called in C:\laragon\www\api-connect.top\vendor\artesaos\defender\src\Defender\Traits\Models\Permission.php on line 79`

**Comment by Helmesvs** [comment]
Estou com o mesmo erro... O jeito é trocar de pacote
