### ISSUE TITLE
Not compatible with Laravel 6

### ISSUE THREAD

**Issue by arthurcvm** [artesaos/defender#145]
The project is not compatible with Laravel 6, and the command "composer require artesaos/defender" not get the compatible installation with the version of Framework, see the error bellow:

Problem 1
    - Conclusion: don't install artesaos/defender v0.8.3
    - Conclusion: remove laravel/framework v6.2.0
    - Installation request for artesaos/defender ^0.8.3 -> satisfiable by artesaos/defender[0.8.x-dev, v0.8.3].
    - Conclusion: don't install laravel/framework v6.2.0
    - artesaos/defender 0.8.x-dev requires illuminate/view ~5.6 -> satisfiable by illuminate/view[5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/view 5.6.x-dev|don't install laravel/framework v6.2.0
    - don't install illuminate/view 5.7.17|don't install laravel/framework v6.2.0
    - don't install illuminate/view 5.7.18|don't install laravel/framework v6.2.0
    - don't install illuminate/view 5.7.19|don't install laravel/framework v6.2.0
    - don't install illuminate/view 5.7.x-dev|don't install laravel/framework v6.2.0
    - don't install illuminate/view 5.8.x-dev|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.0|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.1|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.10|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.11|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.12|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.13|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.14|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.15|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.16|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.17|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.19|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.2|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.20|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.21|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.22|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.23|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.24|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.25|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.26|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.27|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.28|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.29|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.3|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.30|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.31|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.32|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.33|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.34|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.35|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.36|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.37|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.38|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.39|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.4|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.5|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.6|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.7|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.8|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.6.9|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.0|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.1|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.10|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.11|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.15|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.2|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.20|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.21|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.22|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.23|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.26|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.27|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.28|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.3|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.4|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.5|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.6|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.7|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.8|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.7.9|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.0|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.11|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.12|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.14|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.15|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.17|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.18|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.19|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.2|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.20|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.22|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.24|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.27|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.28|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.29|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.3|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.30|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.31|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.32|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.33|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.34|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.35|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.4|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.8|don't install laravel/framework v6.2.0
    - don't install illuminate/view v5.8.9|don't install laravel/framework v6.2.0
    - Installation request for laravel/framework (locked at v6.2.0, required as ^6.0) -> satisfiable by laravel/framework[v6.2.0].

**Comment by arthurcvm** [comment]
I solve the installation problem with the different version flag:

`{
    "require": {
        "artesaos/defender": "dev-master"
    }
}`

Based in the [Packagist](https://packagist.org/packages/artesaos/defender#dev-master) of the project.

**Comment by mauri870** [comment]
@arthurcvm The version `~0.9.0` has been published with support for Laravel 6. Always prefer to use a stable version over a branch.
