### ISSUE TITLE
Middleware em controllers

### ISSUE THREAD

**Issue by wemersonjanuario** [artesaos/defender#20]
Como usar o middleware "needsPermission" no controller para proteger métodos ao invés de usar nas routes? preciso especificar quais permissões necessárias determinados métodos precisam no controller, para os casos de rotas RESTful

**Comment by andreoav** [comment]
Vc pode utilizar a API do defender. No seu metodo vc pode fazer uma verificação usando o Defender::can().

**Comment by wemersonjanuario** [comment]
Correto, pensei que tinha algo pra usar no constructor tipo:
fica a sugestão.

$this->middleware('needsPermission',[
'defend_methods' => [
'inserir_usuario' => ['nomeMetodo', 'outroMetodo']]
]);

**Comment by andreoav** [comment]
Até daria, mas o laravel interpreta apenas as chaves only e except no middleware do construct do controller.
