### ISSUE TITLE
Add a middleware exception when unauthorized

### ISSUE THREAD

**Issue by andreoav** [artesaos/defender#21]
Throw an exception when the user doesn't have permission.
An exception allows project specific customization using the laravel exception handler.

**Comment by tchicotti** [comment]
I would like to make a suggestion. Allow specifying a callback on the routes file if launched the exception, or something like that

**Comment by andreoav** [comment]
Commit 6b1e3731825ad68b70deb829f8867ba4972a5dfc closes this issue.
