### ISSUE TITLE
Add multi auth support

### ISSUE THREAD

**Issue by andreoav** [artesaos/defender#36]

**Comment by vinicius73** [comment]
The use of both is possible, but some parts of the stand as the middleware can not be used directly, and to defend the class needs to be extended.

There are some things that can be done to facilitate the process.
We're working on it right now, but I think q will be for v0.4

**Comment by vinicius73** [comment]
Support the multi-auth is pretty simple.
In recent updates you can later add the following code:

```php
 app()->singleton('defender.auth', function ($app) {
       return $app['auth']->admin();
  });
```

That everything will work normally.
