### ISSUE TITLE
Blade @is() support for multiple roles

### ISSUE THREAD

**Issue by lowerends** [artesaos/defender#41]
Is there a way to add multiple roles in the Blade `@is()` extension?

**Comment by vinicius73** [comment]
Already on our list @lowerends 
This and some other improvements came in the next release

Thanks for the suggestion

**Comment by lowerends** [comment]
Great!

Let me know if I can help.

**Comment by vinicius73** [comment]
If you already have a solution for this, just send a PR.
We would be happy to accept!

**Comment by lowerends** [comment]
OK, I'll have a look to create a PR.

I was thinking of replacing the User `hasRole($role)` function by a `hasRoles($roles, $any)` function that would accept a single string or an array of strings and add an extra parameter `$any` for returning true if the user has any one of the given roles.

Do you prefer replacing the function `hasRole()` by `hasRoles() or adding `hasRoles` separately?

**Comment by vinicius73** [comment]
hasRoles I find most correct.
@vluzrmos @andreoav

**Comment by andreoav** [comment]
Is and hasRoles are equivalent 
Sent using Boxer
Em 10/06/2015 10:48, Vinicius Reis <notifications@github.com> escreveu:hasRoles I find most correct.
@vluzrmos @andreoav

**Comment by lowerends** [comment]
@vinicius73 Do you mean you find it most correct to replace `hasRole` with `hasRoles`?

**Comment by andreoav** [comment]
@vinicius73 @lowerends Since we are using `can` to check permissions, and to make the API consistent, I think `is` is better.

To not break the API, we `is` must accept both a string, or an array of roles.

**Comment by lowerends** [comment]
Fixed with PR #43.
