### ISSUE TITLE
Proposal: add command line helpers

### ISSUE THREAD

**Issue by vluzrmos** [artesaos/defender#49]
add some command line helpers like:

![image](https://cloud.githubusercontent.com/assets/450848/8630646/d807559c-273e-11e5-870e-381d798a9894.png)

**Comment by vluzrmos** [comment]
#51 and branch [feature-add-commands](https://github.com/artesaos/defender/tree/feature-add-commands).

Thanks for @Limaa .

**Comment by vinicius73** [comment]
Any updates?

**Comment by Limaa** [comment]
This week I'll probably have some time to work on this
