### ISSUE TITLE
Commands!

### ISSUE THREAD

**Issue by emtudo** [artesaos/defender#52]
[English]

I've tested the commands, that is very cool!

I would like to propose some improvements:

1 - One option to attach permission to a user, even if that permission already exists.
2 - A command to list permissions of the user like `defender:permissions user`
3 - A command to list roles of the user like `defender:roles user`
4 - Command to detach permissions for users
5 - Command to remove permissions
5 - Command to remove roles
6 - Command to add/remove temporary permissions

====

[Português]

Testei os comandos, muito show!

Gostaria de sugerir melhorias:

1 - Ter opção de poder adicionar um usuário a uma permissão existente, sem precisar criar;
2 - Ter como lista permissões do usuário algo como artisan defender:permissions user
3 - Ter como lista roles do usuário algo como artisan defender:roles user
4 - Poder remover permissões do usuário
5 - Poder apagar permissoes
6 - adicionar/remover permissões  temporaria
7 - tudo que falei de permissões também para roles

**Comment by vluzrmos** [comment]
#49 #51

**Comment by Limaa** [comment]
Que tal ago assim?

![image](https://cloud.githubusercontent.com/assets/4899111/8638790/0f8fe956-28c6-11e5-82aa-61e724e072f8.png)

**Comment by vluzrmos** [comment]
--expires deve ser uma string aceita Carbon.

Achei legal a proposta. :+1:

**Comment by vluzrmos** [comment]
php artisan defender:permissions:clear-expired

**Comment by emtudo** [comment]
Muito legal!
