### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by lsobral** [artesaos/defender#53]
Há alguma especificação diferente para a versão 5.1 do Laravel?

**Comment by vluzrmos** [comment]
Olá @lsobral , pode especificar o problema que está encontrando ?

Acredito que a única coisa que mudou foi o namespace da trait HasDefender.

**Comment by lsobral** [comment]
Olá @vluzrmos 

Está funcionado agora. Eu atualizei para a nova versão e refiz as tabelas, comecei do zero.

Eu tinha seguido os passos dados no Git e mudei apenas algumas coisas para adaptar.

Eu inclui no Provider em config/app.php o ::class no final
`Artesaos\Defender\Providers\DefenderServiceProvider::class`

E para o Facade também
`'Defender' => Artesaos\Defender\Facades\Defender::class,`

E também no Kernel:
`// Controle de acesso usando permissões`
`'needsPermission' => Artesaos\Defender\Middlewares\NeedsPermissionMiddleware::class,`

`// Controle de acesso mais simples, utiliza apenas os grupos`
`'needsRole' => Artesaos\Defender\Middlewares\NeedsRoleMiddleware::class`

Agora está funcionando.
O Readme em inglês está um pouco confuso depois que vocês atualizaram.

Obrigado.

**Comment by vluzrmos** [comment]
Olá @lsobral , 
Vamos tentar melhorar o readme e esperamos que na versão 0.4 não esteja confuso, obrigado pelo feedback! :+1: 


@andreoav @vinicius73
