### ISSUE TITLE
É possível usar needsRole em Route Groups

### ISSUE THREAD

**Issue by lsobral** [artesaos/defender#55]
Tentei fazer o seguinte, mas não dá erro, apenas uma tela em branco. Não aparece nada nos logs para eu poder ajudar. O que eu estou fazendo errado?

`Route::group([ 'prefix' => 'admin', 'middleware' => ['auth', 'needsRole'], 'is' => 'admin' ], function() {

    Route::get('/', ['as' => 'admin.painel', 'uses' => 'PainelController@index']);

});`

**Comment by emtudo** [comment]
sim é possível, está tudo normal.
Geralmente tala em branco é questões de permissão na pasta storage. by @vluzrmos  
Já conferiu as permissões da pasta?

**Comment by vluzrmos** [comment]
@lsobral verifica se funciona dessa forma:

```php
Route::group([ 'prefix' => 'admin', 'middleware' => ['auth', 'needsRole:admin']], function() {
     Route::get('/', ['as' => 'admin.painel', 'uses' => 'PainelController@index']);
});
```

Se funcionar, temos algum erro com a forma que era feito no L5.0

**Comment by emtudo** [comment]
ainda uso a forma antiga @vluzrmos .

**Comment by lsobral** [comment]
@vluzrmos não funcionou. Aparece a tela em branco.
Talvez tenha algum coisa pegando com a versão 5.1

`Laravel Framework version 5.1.7 (LTS)`

@emtudo Acredito que a tela em branco não tenha a ver com o storage neste caso, pois há permissões nesta pasta. Se eu retiro o *needsRole* do route, funciona como deveria mostrando a tela se logado apenas. Assim funciona:

```php
Route::group([ 'prefix' => 'admin', 'middleware' => 'auth'], function() {
     Route::get('/', ['as' => 'admin.painel', 'uses' => 'PainelController@index']);
});
```

@vluzrmos fiz um teste usando o Defender dentro do Controller e retirando do route e parece que o middleware não é executado

```php
$this->middleware('needsRole:admin');
```

Será que alguém já tentou no 5.1, posso estar fazendo algo errado. Como posso debugar?

**Comment by emtudo** [comment]
estou usando no 5.1 sem problema amigo. vc seguiu certo o manual?
Não sei o que pensar. vamos por passo rsrsrs, tente usar no controle ao invés de ser na rota para ver.

**Comment by vluzrmos** [comment]
Lembrando que no controller deve fazer isso dentro do __construct()

**Comment by vinicius73** [comment]
@lsobral entrei em contato com você pelo seu facebook

**Comment by lsobral** [comment]
Problema resolvido colocando uma barra invertida na frente do caminho dos middlewares do Defender.

```php
protected $routeMiddleware = [
       'auth'          => \App\Http\Middleware\Authenticate::class,
       'auth.basic'    => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
       'guest'         => \App\Http\Middleware\RedirectIfAuthenticated::class,        // Controle de acesso usando permissões
       'needsPermission' => **\Artesaos\Defender\Middlewares\NeedsPermissionMiddleware::class**,        // Controle de acesso mais simples, utiliza apenas os grupos
       'needsRole' => **\Artesaos\Defender\Middlewares\NeedsRoleMiddleware::class**
   ]; 
```

**Comment by lsobral** [comment]
Problema resolvido colocando uma barra invertida na frente do caminho dos middlewares do Defender.

```php
protected $routeMiddleware = [
       'auth'          => \App\Http\Middleware\Authenticate::class,
       'auth.basic'    => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
       'guest'         => \App\Http\Middleware\RedirectIfAuthenticated::class,        // Controle de acesso usando permissões
       'needsPermission' => \Artesaos\Defender\Middlewares\NeedsPermissionMiddleware::class,        // Controle de acesso mais simples, utiliza apenas os grupos
       'needsRole' => \Artesaos\Defender\Middlewares\NeedsRoleMiddleware::class
   ]; 
```
