### ISSUE TITLE
Problema com as rotas

### ISSUE THREAD

**Issue by raphaeljorge** [artesaos/defender#56]
Eu criei as seguintes regras: superadmin, admin, user.

Coloquei 1 usuário com a regra de superadmin no usuário e mesmo assim, ao usar a rota desta forma: 
```php
Route::get('foo', ['middleware' => ['auth', 'needsRole'], 'can' => ['admin', 'patient'], function()
{
    return 'Yes I am!';
}]);
```
Recebo o retorn

Desta forma: 
```php
Route::get('foo', ['middleware' => ['auth', 'needsRole:superadmin'], function() {
    return 'Yes I am!';
}]);
```
Só funciona se eu passar apenas uma regra se eu adicionar um |admin, nem o primeiro nem as outras funcionam.

**Comment by andreoav** [comment]
@raphaeljorge Qual a versão do laravel que vc está usando

**Comment by emtudo** [comment]
como vc não está usando a opção "any" com valor "true" a usuário precisa ter as duas permissões.

**Comment by emtudo** [comment]
detalhe: nome das permissões ou roles não influencia, influencia o que vc programa.

**Comment by raphaeljorge** [comment]
@andreoav 

Laravel Framework version 5.1.7 (LTS)

@emtudo 

Não utilizo "any" como "true" pois para estas rotas, minha ideia é deixar com que membros com algumas roles possam acessar. A hierarquia é de um sistema hospitalar.

**Comment by emtudo** [comment]
não entendi muito bem o que vc disse.
mas explicando apenas caso não tenha entendi, se tiver entendido, desconsidere meu mico por favor rsrsrs, mas a forma que vc está fazendo, vc está exigindo que o membro em questão tenha acesso ao grupo "admin" e ao "patient", se ele tiver apenas acesso a um dos grupos ele não vai conseguir acessar.

**Comment by raphaeljorge** [comment]
@emtudo Na verdade é ao contrário, por exemplo, tenho o usuário admin, doctor, nurse, patient. Só quero que usuários que tenham as permissões admin, doctor e nurse consigam entrar na página, exceto patient.

**Comment by emtudo** [comment]
usuário ou grupo (roles)? admin, doctor, nurse e patient? São usuários ou grupos?

**Comment by raphaeljorge** [comment]
Eu consegui fazer a verificação agora, mantive desta forma:
```php
Route::get('foo', ['middleware' => ['auth', 'needsRole'], 'is' => ['superadmin', 'admin', 'doctor', 'nurse'], 'any' => true, function()
{
    return 'Yes I am!';
}]);
```
Obrigado por ajudarem.
