### ISSUE TITLE
Config cache not possible due to closure in config

### ISSUE THREAD

**Issue by lowerends** [artesaos/defender#58]
I noticed that it is not possible to use `php artisan config:cache` when using Defender. The reason for this is the following lines in the config file, where a closure is used:

```
/*
* Forbidden callback
*/
'forbidden_callback' => function () {
    throw new \Artesaos\Defender\Exceptions\ForbiddenException();
},
```
It seems to be bad practice to use closures in a config file. Is there a way to avoid using a closure here? I found a similar issue here: https://github.com/lucadegasperi/oauth2-server-laravel/issues/323.

**Comment by andreoav** [comment]
Got it..
We'll find another way to handle the forbidden_callback feature.

Since it will introduce a breaking change it should be fixed in the next major version,

**Comment by lowerends** [comment]
Great. If I can be of any help, let me know!

**Comment by lowerends** [comment]
Thanks for releasing this fix!
