### ISSUE TITLE
Replace can method and blade extensions

### ISSUE THREAD

**Issue by andreoav** [artesaos/defender#60]
With the introduction of Laravel offical ACL layer we need a way to remove the conflict with the official can @can and endcan.

Since this is a breaking change, we'll need a major release.

**Comment by luanrodrigues** [comment]
has Laravel an offical ACL??? I didn't know that where are the docs?

**Comment by andreoav** [comment]
@luanrodrigues http://laravel.com/docs/5.1/authorization

**Comment by vinicius73** [comment]
Laravel 5.1.11 @luanrodrigues

**Comment by andreoav** [comment]
`can -> may`

Can1 and may1 are frequently but not always interchangeable in senses indicating possibility:  A power failure can  (or may) occur at any time. Despite the insistence by some, that can means only “to be able” and may means “to be permitted,” both are regularly used in seeking or granting permission:  Can  (or May) I borrow your tape recorder? You can (or may) use it tomorrow. Sentences using can occur chiefly in spoken English. May in this sense occurs more frequently in formal contexts:  May I address the court, Your Honor?  In negative constructions, can't or cannot is more common than may not:  You can't have it today. I need it myself.  The contraction mayn't is rare.  Can but and cannot but are formal and now somewhat old-fashioned expressions suggesting that there is no possible alternative to doing something. Can but is equivalent to can only:  We can but do our best.  Cannot but is the equivalent of cannot help but:  We cannot but protest against these injustices.  See also cannot, help.  

Source: http://www.thesaurus.com/browse/can

**Comment by luanrodrigues** [comment]
thank you all

**Comment by vinicius73** [comment]
How about we change to `@canDo`?

**Comment by tecnical** [comment]
I sugest to change to @hasPermisison or to @canDo how @vinicius73 commented.

**Comment by vinicius73** [comment]
`@userCan` it's more redable for me.

**Comment by andreoav** [comment]
I don't think `@userCan` is the best solution... 90% of the time we use permission with users... but it can have other uses..

This is why I support the `hasPermission` option.

**Comment by andtxr** [comment]
Hello guys.

While talking with @vinicius73 we thought about to use @isAuthorized as new method name.

**Comment by tecnical** [comment]
Will @isAuthorized not make any confusion with @is?

**Comment by vinicius73** [comment]
now this helper is `@shield`
