### ISSUE TITLE
Interface 'Artesaos\Defender\Contracts\User' not found

### ISSUE THREAD

**Issue by wemersonjanuario** [artesaos/defender#63]
Having problem while upgrading to 0.4.1 version.
The Documentation says to implement the interface Artesaos\Defender\Contracts\User on Users's class but there's no User.php file located in Contracts dir.

I have this error on console.
Interface 'Artesaos\Defender\Contracts\User' not found

**Comment by vinicius73** [comment]
hi @wemersonjanuario 
v0.4.1 is beta, but this error can be fixed
change yo `Artesaos\Defender\Contracts\Repositories\UserRepository`

**Comment by wemersonjanuario** [comment]
Is this a temporary solution? I don't want to implement all the methods. Can use only the HasDefender trait to give users the dedender functionality?

**Comment by andreoav** [comment]
You don't need to implement the repository, just remove the DefenderContract from your User model. 

The documentation will be updated soon the reflect the changes

**Comment by andreoav** [comment]
You don't need to implement the repository, just remove the DefenderContract from your User model. 

The documentation will be updated soon the reflect the changes

**Comment by wemersonjanuario** [comment]
Nice, Thanks guys.
