### ISSUE TITLE
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Gate' not found' 

### ISSUE THREAD

**Issue by damon8765** [artesaos/defender#68]
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Gate' not found'

**Comment by damon8765** [comment]
Why the problem with @can

**Comment by damon8765** [comment]
Urgent

**Comment by andreoav** [comment]
@damon8765 The new version 0.4 doesn't uses the `can` syntax.
Can you explain your problem?

**Comment by vinicius73** [comment]
@damon8765 
The error reported makes reference to Gath, who do not have relation with this package.
By sight error you not properly imported the class or facade

**Comment by damon8765** [comment]
Version of the problem, but the upgrade version of the super administrator also has a problem, or the label '@hasPermission' is also a problem

**Comment by vinicius73** [comment]
@damon8765 defender not use @hasPermission, now it use @shield

**Comment by damon8765** [comment]
ok Thank you
