### ISSUE TITLE
How get $user->getAllPermisiion();

### ISSUE THREAD

**Issue by apsana** [artesaos/defender#73]
How get $user->getAllPermisiion();

**Comment by vinicius73** [comment]
Which version of you are sweating? @apsana 
There is no mystery to this method, is having an Error?

**Comment by emtudo** [comment]
do use two "ii" ?

try it $user->getAllPermission();

**Comment by apsana** [comment]
I used laravel 5.1

**Comment by vinicius73** [comment]
sorry, what version of defending you using? @apsana

**Comment by vinicius73** [comment]
@emtudo pointed a misspelling in your method.
