### ISSUE TITLE
Model App\User defined on DefenderServiceProvider

### ISSUE THREAD

**Issue by ghsalazar1** [artesaos/defender#76]
Boa tarde pessoal,
Percebi que na linha 98 do arquivo src\Defender\Providers\DefenderServiceProvider.php é definido o model de usuário levando em consideração o Model default do laravel, que fica em "App\User"... Minha pergunta é a seguinte, se por ventura o nome da minha aplicação for modificado ou até mesmo o namespace do Model de usuário for alterado, como devo proceder neste caso?

**Comment by vinicius73** [comment]
Aquilo é o default caso a conf não exista @ghsalazar1 
ela pega diretamente o valor de https://github.com/laravel/laravel/blob/5.1/config/auth.php#L31
Então fique tranquilo :)

**Comment by ghsalazar1** [comment]
Muito brigado @vinicius73 quase tenho um infarte kkk
