### ISSUE TITLE
Validação hasRole recebendo objeto ao invés de string

### ISSUE THREAD

**Issue by tperrelli** [artesaos/defender#78]
Bom dia galera. Eu tava implementando uns códigos aqui, tomando como base a arquitetura do defender, e me deparei com um detalhe…
no arquivo HasRole.php, nas funções hasRole e attachRole…

Enquanto o hasRole faz uma comparação da “string” role no banco, a função attachRole recebe um objeto Role como parâmetro.
O detalhe  é que o attachRole utiliza a função hasRole. Porém, ao passar o parâmetro no hasRole, é passado o objeto, ao invés da string. Como resultado, vai sempre entrar no if, gerando duplicidade das roles.

Isso foi arquitetado propositalmente, ou seria um possível bug? Fiz um composer update, e na minha versão local. essa questão se encontra em:

arquivo HasRole.php
linha 51

**Comment by vinicius73** [comment]
fixed on #79
