### ISSUE TITLE
erro após login

### ISSUE THREAD

**Issue by daniellopes81** [artesaos/defender#89]
Bom dia,

Estou tendo um problema que nao estou encontrando o motivo do mesmo.

quando eu executo o login ele me retorna o seguinte erro:

Whoops, looks like something went wrong.
BadMethodCallException in Builder.php line 2161:
Call to undefined method Illuminate\Database\Query\Builder::hasPermission()

Tem alguma ideia ?

**Comment by vinicius73** [comment]
Mostre seu model user @daniellopes81

**Comment by daniellopes81** [comment]
```
<?php

namespace App;
use Artesaos\Defender\Traits\HasDefender;
use Illuminate\Auth\Authenticatable;


class User extends Authenticatable
{
    use HasDefender;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function setPasswordAttribute($value)
    {
        if (empty($value))
            unset($this->attributes['password']);
        else
            $this->attributes['password'] = bcrypt($value);
    }
}

```

**Comment by mauri870** [comment]
Bom dia @daniellopes81. Pode verificar se em algum arquivo no seu projeto você está chamando o método `hasPermission()`? Creio que vc esteja chamando ele de uma instância d query builder e n do model em si

**Comment by daniellopes81** [comment]
o interessante é que este erro ocorre somente nas rotas protegidas com o "defender"

rota:
```
Route::get('foo', ['middleware' => ['auth', 'needsPermission'], 'shield' => 'users.index', function(){
        return 'Yes I can!';
 }]);
```

veja mais detalhe do erro:

> in Builder.php line 2161
> **at Builder->__call('hasPermission', array('users.index'))**
> **at Builder->hasPermission('users.index')**
> at call_user_func_array(array(object(Builder), 'hasPermission'), array('users.index')) in Builder.php line 1313
> at Builder->__call('hasPermission', array('users.index'))
> at Builder->hasPermission('users.index')
> at call_user_func_array(array(object(Builder), 'hasPermission'), array('users.index')) in Model.php line 3490
> at Model->__call('hasPermission', array('users.index')) in NeedsPermissionMiddleware.php line 36
> at User->hasPermission('users.index') in NeedsPermissionMiddleware.php line 36
> at NeedsPermissionMiddleware->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(NeedsPermissionMiddleware), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 28
> at Authenticate->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 64
> at VerifyCsrfToken->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 62
> at StartSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
> at EncryptCookies->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
> at Pipeline->then(object(Closure)) in Router.php line 726
> at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
> at Router->dispatchToRoute(object(Request)) in Router.php line 675
> at Router->dispatch(object(Request)) in Kernel.php line 246
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
> at Pipeline->then(object(Closure)) in Kernel.php line 132
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
> at Kernel->handle(object(Request)) in index.php line 54
> at require_once('C:\Users\Daniel Lopes\Dropbox\sites\laravel\public\index.php') in server.php line 21

**Comment by daniellopes81** [comment]
@vinicius73, @mauri870 
Conseguem entender onde pode está acontecendo o problema ?
Estou sem entender até agora....

**Comment by mauri870** [comment]
Qual a versão do fw? Testou com uma instalação limpa?

**Comment by atiladelcanton** [comment]
Você colocou no Kerner nas middleware ?

**Comment by daniellopes81** [comment]
Resolvido... fiz uma nova instalação e funcionou
