### ISSUE TITLE
Gerar migrações com data atual (stub)

### ISSUE THREAD

**Issue by andreportaro** [artesaos/defender#91]
Migrations estão sendo geradas com datas de 2015. 

Em qualquer aplicação criada após a data das migrations do pacote, ocorrerá conflito (por exemplo, as migrations criam chaves estrangeiras utilizando a tabela user - mesmo em pacotes cuja primeira migração ainda não foi efetuada).

Seria possível utilizar um stub para criação dos arquivos de migração de acordo com a data?

**Comment by mauri870** [comment]
Isso é uma configuração que depende do projeto... Pra mim por exemplo nunca deu problema, pra vc pode ter ocorrido, etc.
Como as migrations são publicadas e imagino que sejam commitadas após isso, qualquer um pode alterar a ordem das mesmas dependendo do projeto sem problemas

**Comment by vinicius73** [comment]
O problema é que a cada vendor publish as migrations serão publicadas novamente. 
Defender depende apenas da migration de user. 
Então todas as outras não impactam em nada.

**Comment by andreportaro** [comment]
Sim, mas não seria bom levar em conta que o defender pode ser utilizado **em qualquer momento** da vida de um projeto? me parece que foi sempre imaginado que ele só deve ser utilizado depois de rodar as migrações e criações de tables de usuário.

**Comment by vinicius73** [comment]
Defender assume que vc está usando as migrations padrões do Laravel (users)

**Comment by andreportaro** [comment]
Defender assume que você ** já efetuou as migrações padrões do laravel**.

**Comment by vinicius73** [comment]
Só se algo mudou @andreportaro. 
Pode mostrar oq está acontecendo?

**Comment by emtudo** [comment]
@vinicius73 eu acredito que ele esteja falando do nome dos arquivos:

2015_02_23_161101_create_defender_roles_table.php
2015_02_23_161102_create_defender_permissions_table.php
2015_02_23_161103_create_defender_role_user_table.php
2015_02_23_161104_create_defender_permission_user_table.php
2015_02_23_161105_create_defender_permission_role_table.php


No caso o que resolveria seria, que ao copiar com o service provider, alterar o nome dos arquivos para Y_M_D_HMI_RESTANTE-DO-NOME

**Comment by andreportaro** [comment]
É isso que o @emtudo disse, estou pensando aqui se tem uma forma do migration do defender ser gerado com a data "corrente", para que seja os ultimos na "fila" da migração.

**Comment by vinicius73** [comment]
Como comentei lá em cima, fazer isso vai copiar a migration sempre. 
Já tentamos antes. :(

**Comment by andreportaro** [comment]
Valeu @vinicius73. quer fechar aqui? se eu descobrir algo, abro outro ou faço um PR

**Comment by emtudo** [comment]
Poderia fazer um arquivo de configuração para isso.

Mas são tão poucos arquivos que é melhor o cara fazer isso na mão.

**Comment by vinicius73** [comment]
Algum arquivo do Laravel chegou a mudar @emtudo @andreportaro?

**Comment by emtudo** [comment]
@vinicius73 sei não, só achei que não estava entendendo a questão da data, e resolvi tentar explicar. Eu nem tinha lido tudo, só li um dos emails que tinha recebido.

Mas a questão é, tipo geralmente a migration de usuário pelo menos nos meus projetos, é alterado, e acaba tendo outra data mais atual.

Porém até hoje eu não vi nenhum pacote que tenha migrations se preocupar com as datas, acho que no caso sempre seria bom publicar as migrations incluído o nome do service provider, assim o cara neste caso renomeia os arquivos manualmente.

**Comment by vinicius73** [comment]
Então vou fechar a issue.
@andreportaro Se quiser colocar alguma observação no readme sobre isso será bem vinda :)
