### ISSUE TITLE
Change publishing path for database migrations

### ISSUE THREAD

**Issue by VeeeneX** [artesaos/defender#96]
Migrations should be pushed right to migrations folder, even if user has its own path for it.
To fix this, change ServiceProvider to:

``` php
    /**
     * Publish migration file.
     */
    private function publishMigrations()
    {
        $this->publishes([__DIR__.'/../../resources/migrations/' => database_path('database/migrations')], 'migrations');
    }
```

(I'm busy to pull a request sorry :) )

**Comment by torkiljohnsen** [comment]
… or perhaps just use `$provider->loadMigrationsFrom()` so you don't have to push the migrations anywhere.
