### ISSUE TITLE
afterResolving not firing anymore

### ISSUE THREAD

**Issue by NoviCMS** [artesaos/defender#97]
Hello,

i have a problem with the @shield commands in my blade files... found that this line:

$this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
DefenderServiceProvider.php line: 118

is not firing... and the @shield lines get printed.

i have installed the latest 5.1.\* update

**Comment by NoviCMS** [comment]
also: 

\Blade::directive('shield', function($expression) {
            return "<?php if(app('defender')->canDo{$expression}): ?>";
        });

        \Blade::directive('endshield', function($expression) {
            return '<?php endif; ?>';
        });

is not working

**Comment by NoviCMS** [comment]
Found the problem. Using htmlmin will result in this issue

**Comment by rafaelqm** [comment]
@NoviCMS how did you solve this problem?
